AWSTemplateFormatVersion: "2010-09-09"

Description: |
  GitHub Actions Terraform lab stack.
  Creates:
    - An S3 bucket for Terraform state (CloudFormation-assigned name)
    - An IAM Role ("service account") assumable by GitHub Actions via OIDC,
      locked to a single GitHub repository, with EC2 and S3 admin permissions.

  NOTE: An OIDC provider for token.actions.githubusercontent.com must already
  exist in this AWS account:
    arn:aws:iam::<ACCOUNT_ID>:oidc-provider/token.actions.githubusercontent.com

Parameters:
  GitHubRepository:
    Description: GitHub repository in GITHUB_OWNER_NAME/GITHUB_REPO_NAME format used to lock the OIDC trust policy.
    Type: String
    Default: GITHUB_OWNER_NAME/GITHUB_REPO_NAME

Resources:
  # ------------------------------------------------------------
  # S3 Bucket for Terraform State (name assigned by CloudFormation)
  #
  # NOTE: Deleting the stack will not delete the bucket or its objects.
  # Other resources will be removed but the bucket stays and will
  # to be removed manually later.  This is due to CloudFormation not
  # being able to delete the bucket contents before removing the bucket.
  # This approach is a best practice for Terraform to prevent the loss of
  # state information related to resources that have already been deployed.
  #
  # ------------------------------------------------------------
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  # (Optional but recommended) Explicitly enforce TLS for bucket access
  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${TerraformStateBucket}
              - !Sub arn:${AWS::Partition}:s3:::${TerraformStateBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  # ------------------------------------------------------------
  # Role assumed by GitHub Actions via OIDC, locked to one repo
  # ------------------------------------------------------------
  TerraformServiceAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-TerraformServiceAccountRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeRoleWithGithubOidc
            Effect: Allow
            Principal:
              Federated: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubRepository}:*

      # Attach “admin-ish” permissions as requested
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  # ------------------------------------------------------------
  # (Optional) Extra permissions commonly needed for Terraform state backends
  # and AWS account introspection. Keep or remove as you like.
  # ------------------------------------------------------------
  TerraformServiceAccountExtras:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-TerraformServiceAccountExtras
      Roles:
        - !Ref TerraformServiceAccountRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Some Terraform workflows read account identity/region data
          - Sid: ReadIdentity
            Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: "*"

Outputs:
  AwsRegion:
    Description: Use this value for the repository variable AWS_REGION
    Value: !Ref AWS::Region

  TerraformServiceAccountRoleArn:
    Description: Use this value for the repository variable AWS_ROLE_ARN
    Value: !GetAtt TerraformServiceAccountRole.Arn

  TerraformStateBucketName:
    Description: Use this value for the repository variable TERRAFORM_STATE_BUCKET
    Value: !Ref TerraformStateBucket
